# Generated by Django 5.0.6 on 2024-05-29 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfEating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('kcal', models.IntegerField(blank=True, null=True, verbose_name='Calories')),
                ('protein', models.IntegerField(blank=True, null=True, verbose_name='Protein')),
            ],
            options={
                'verbose_name': 'Day of eating',
                'verbose_name_plural': 'Days of eating',
            },
        ),
    ]
